<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.irs.gov/efile"
           xmlns:t="http://www.irs.gov/efile"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <xs:element name="Transmission" type="t:TransmissionType"/>

    <xs:complexType name="TransmissionType">
        <xs:sequence>
            <xs:element name="TransmissionHeader" type="t:TransmissionHeaderType"/>
            <xs:element name="TobCigFiling" type="t:TobCigFilingType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TransmissionHeaderType">
        <xs:sequence>
            <xs:element name="Jurisdiction" type="xs:string"/>
            <xs:element name="TransmissionID" type="xs:string"/>
            <xs:element name="Timestamp" type="xs:dateTime"/>
            <xs:element name="Transmitter" type="xs:string"/>
            <xs:element name="ProcessType">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="T"/>
                        <xs:enumeration value="P"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TobCigFilingType">
        <xs:sequence>
            <xs:element name="SubmissionId" type="xs:string"/>
            <xs:element name="TobaccoCigaretteHeader" type="t:ReturnHeaderType"/>
            <xs:choice>
                <xs:element name="CigaretteSecondaryWholesalerReturn" type="t:CigaretteReturnType"/>
                <xs:element name="TobaccoSecondaryWholesalerReturn" type="t:OtpReturnType"/>
                <xs:element name="CigaretteUnclassifiedAcquirerReturn" type="t:CigaretteUaReturnType"/>
                <xs:element name="TobaccoUnclassifiedAcquirerReturn" type="t:OtpReturnType"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ReturnHeaderType">
        <xs:sequence>
            <xs:element name="Jurisdiction" type="xs:string"/>
            <xs:element name="Timestamp" type="xs:dateTime"/>
            <xs:element name="TaxPeriodEndDate" type="xs:date"/>
            <xs:element name="TypeOfFiling" type="xs:string"/>
            <xs:element name="Filer" type="t:FilerType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="FilerType">
        <xs:sequence>
            <xs:element name="FEIN" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CigaretteReturnType">
        <xs:sequence>
            <xs:element name="reportCurrency" type="xs:string"/>
            <xs:element name="StateLicenseNumber" type="xs:string"/>
            <xs:choice>
                <xs:element name="CigSndWholeSchedule" type="t:CigaretteScheduleListType"/>
                <xs:element name="CigUnAcqSchedule" type="t:CigaretteScheduleListType"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CigaretteUaReturnType">
        <xs:sequence>
            <xs:element name="reportCurrency" type="xs:string"/>
            <xs:element name="StateLicenseNumber" type="xs:string"/>
            <xs:element name="CigUnAcqSchedule" type="t:CigaretteScheduleListType" minOccurs="0"/>
            <xs:element name="BeginningUnaffixedInventory" type="t:StampCountsType"/>
            <xs:element name="EndingUnaffixedInventory" type="t:StampCountsType"/>
            <xs:element name="BeginningAffixedInventory" type="t:StampCountsType"/>
            <xs:element name="EndingAffixedInventory" type="t:StampCountsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OtpReturnType">
        <xs:sequence>
            <xs:element name="reportCurrency" type="xs:string"/>
            <xs:element name="StateLicenseNumber" type="xs:string"/>
            <xs:choice>
                <xs:element name="TobSndWholeSchedule" type="t:OtpScheduleListType"/>
                <xs:element name="TobUnAcqSchedule" type="t:OtpScheduleListType"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CigaretteScheduleListType">
        <xs:sequence>
            <xs:element name="Schedule" type="t:CigaretteScheduleType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OtpScheduleListType">
        <xs:sequence>
            <xs:element name="Schedule" type="t:OtpScheduleType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CigaretteScheduleType">
        <xs:sequence>
            <xs:element name="ScheduleCode" type="xs:string"/>
            <xs:element name="DateReceived" type="xs:date"/>
            <xs:element name="InvoiceDate" type="xs:date"/>
            <xs:element name="InvoiceNumber" type="xs:string"/>
            <xs:element name="PurchaserSellerFEIN" type="xs:string"/>
            <xs:element name="PurchaserSellerName" type="xs:string"/>
            <xs:element name="BrandCode" type="xs:string"/>
            <xs:element name="CigPackSize" type="xs:string"/>
            <xs:element name="PackCount" type="xs:string"/>
            <xs:element name="Address" type="t:AddressType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OtpScheduleType">
        <xs:sequence>
            <xs:element name="ScheduleCode" type="xs:string"/>
            <xs:element name="DateReceivedOrSold" type="xs:date"/>
            <xs:element name="InvoiceDate" type="xs:date"/>
            <xs:element name="InvoiceNumber" type="xs:string"/>
            <xs:element name="PurchaserSellerFEIN" type="xs:string"/>
            <xs:element name="PurchaserSellerName" type="xs:string"/>
            <xs:element name="BrandCode" type="xs:string"/>
            <xs:element name="WholesalePrice" type="xs:decimal"/>
            <xs:element name="TotalOz" type="xs:decimal" minOccurs="0"/>
            <xs:element name="StickCount" type="xs:string" minOccurs="0"/>
            <xs:element name="Address" type="t:AddressType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AddressType">
        <xs:sequence>
            <xs:element name="USAddress" type="t:USAddressType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="USAddressType">
        <xs:sequence>
            <xs:element name="AddressLine1" type="xs:string"/>
            <xs:element name="City" type="xs:string"/>
            <xs:element name="State" type="xs:string"/>
            <xs:element name="ZIPCode" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="StampCountsType">
        <xs:sequence>
            <xs:element name="R1" type="xs:integer"/>
            <xs:element name="R2" type="xs:integer"/>
            <xs:element name="R3" type="xs:integer"/>
            <xs:element name="R4" type="xs:integer"/>
            <xs:element name="R5" type="xs:integer"/>
            <xs:element name="R6" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
